# backend/pdf_module.py
import io
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

def generate_pdf(patient, analysis_text):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    story = []

    title = "<b>HEALTHCARE ASSISTANT - MEDICAL REPORT</b>"
    story.append(Paragraph(title, styles["Title"]))
    story.append(Spacer(1, 15))

    patient_data = [["Patient Name:", patient], ["Report Date:", datetime.now().strftime("%Y-%m-%d")], ["Generated By:", "AI Healthcare Assistant"]]
    table = Table(patient_data, colWidths=[120, 350])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
        ("FONTNAME",(0,0),(-1,-1),"Helvetica"),
        ("FONTSIZE",(0,0),(-1,-1),11),
        ("GRID",(0,0),(-1,-1),0.5,colors.grey),
        ("BOX",(0,0),(-1,-1),1,colors.black),
    ]))
    story.append(table)
    story.append(Spacer(1,20))

    story.append(Paragraph("<b>AI Summary:</b>", styles["Heading2"]))
    story.append(Spacer(1,8))
    formatted_text = (analysis_text or "").replace("\n", "<br/>")
    story.append(Paragraph(formatted_text, styles["BodyText"]))
    story.append(Spacer(1,20))
    story.append(Spacer(1,30))
    story.append(Paragraph("<b>Doctor's Signature:</b> _______________________", styles["Normal"]))
    story.append(Paragraph("This report was auto-generated using the AI Healthcare Assistant.", styles["Italic"]))
    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes

def generate_prescription_pdf(patient, doctor, symptoms, diagnosis, medicines):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = getSampleStyleSheet()
    story = []

    title = "<b>ONLINE PRESCRIPTION</b>"
    story.append(Paragraph(title, styles["Title"]))
    story.append(Spacer(1, 15))

    header_data = [["Patient Name:", patient], ["Doctor:", doctor], ["Date:", datetime.now().strftime("%Y-%m-%d")]]
    table = Table(header_data, colWidths=[120, 350])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BOX", (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(table)
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>Symptoms:</b>", styles["Heading2"]))
    story.append(Paragraph((symptoms or "Not provided").replace("\n","<br/>"), styles["BodyText"]))
    story.append(Spacer(1,8))
    story.append(Paragraph("<b>Diagnosis:</b>", styles["Heading2"]))
    story.append(Paragraph(diagnosis or "Not provided", styles["BodyText"]))
    story.append(Spacer(1,8))
    story.append(Paragraph("<b>Prescription:</b>", styles["Heading2"]))
    if medicines:
        for med in medicines:
            story.append(Paragraph(f"- {med}", styles["BodyText"]))
    else:
        story.append(Paragraph("No medicines provided.", styles["BodyText"]))

    story.append(Spacer(1,20))
    story.append(Paragraph("<b>Doctor's Signature:</b> _______________________", styles["Normal"]))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
